package red.bofan.model;

import java.io.Serializable;
import java.util.Date;

public class Cipher implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.fhint
     *
     * @mbggenerated
     */
    private String fhint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.shint
     *
     * @mbggenerated
     */
    private String shint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.thint
     *
     * @mbggenerated
     */
    private String thint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cipher.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cipher
     *
     * @mbggenerated
     */
    public Cipher(String id, String title, String userId, Date publishTime, String answer, String fhint, String shint, String thint, String content) {
        this.id = id;
        this.title = title;
        this.userId = userId;
        this.publishTime = publishTime;
        this.answer = answer;
        this.fhint = fhint;
        this.shint = shint;
        this.thint = thint;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cipher
     *
     * @mbggenerated
     */
    public Cipher() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.id
     *
     * @return the value of cipher.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.id
     *
     * @param id the value for cipher.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.title
     *
     * @return the value of cipher.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.title
     *
     * @param title the value for cipher.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.user_id
     *
     * @return the value of cipher.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.user_id
     *
     * @param userId the value for cipher.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.publish_time
     *
     * @return the value of cipher.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.publish_time
     *
     * @param publishTime the value for cipher.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.answer
     *
     * @return the value of cipher.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.answer
     *
     * @param answer the value for cipher.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.fhint
     *
     * @return the value of cipher.fhint
     *
     * @mbggenerated
     */
    public String getFhint() {
        return fhint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.fhint
     *
     * @param fhint the value for cipher.fhint
     *
     * @mbggenerated
     */
    public void setFhint(String fhint) {
        this.fhint = fhint == null ? null : fhint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.shint
     *
     * @return the value of cipher.shint
     *
     * @mbggenerated
     */
    public String getShint() {
        return shint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.shint
     *
     * @param shint the value for cipher.shint
     *
     * @mbggenerated
     */
    public void setShint(String shint) {
        this.shint = shint == null ? null : shint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.thint
     *
     * @return the value of cipher.thint
     *
     * @mbggenerated
     */
    public String getThint() {
        return thint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.thint
     *
     * @param thint the value for cipher.thint
     *
     * @mbggenerated
     */
    public void setThint(String thint) {
        this.thint = thint == null ? null : thint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cipher.content
     *
     * @return the value of cipher.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cipher.content
     *
     * @param content the value for cipher.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}