package red.bofan.dao;

import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;
import red.bofan.model.Cipher;
import red.bofan.model.CipherLog;
import red.bofan.model.User;

/**
 * Created by DELL on 2018/2/5.
 */
@Component
public interface CipherLogMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Delete({
            "delete from cipher_log",
            "where log_id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Insert({
            "insert into cipher_log (log_id, cipher_id,submit_answer,user_id,user_name,submit_ip, create_time,create_user,update_time,",
            "update_user)",
            "values (#{logId,jdbcType=VARCHAR}, #{cipherId,jdbcType=VARCHAR},#{submitAnswer,jdbcType=VARCHAR},#{userId,jdbcType=VARCHAR},#{userName,jdbcType=VARCHAR},#{submitIp,jdbcType=VARCHAR},#{createTime,jdbcType=VARCHAR},#{createUser,jdbcType=VARCHAR},#{updateTime,jdbcType=VARCHAR}, ",
            "#{updateUser,jdbcType=VARCHAR})"
    })
    int insert(CipherLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(CipherLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
/*    @Select({
            "select",
            "log_id, cipher_id,submit_answer,user_id,user_name,submit_ip, create_time,create_user,update_time,update_user",
            "from cipher_log",
            "where log_id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Cipher selectByPrimaryKey(String id);*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cipher record);

}
